/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

/**
 *
 * @author HP
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddStudentPanel = new javax.swing.JPanel();
        AddStudent1 = new javax.swing.JLabel();
        AddTeacherPanel = new javax.swing.JPanel();
        AddTeacher1 = new javax.swing.JLabel();
        viewStudentPanel = new javax.swing.JPanel();
        ViewStudentTable1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        viewTeacherPanel = new javax.swing.JPanel();
        viewTeacherTable1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        forViewTeacher = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TeacherDataTable = new javax.swing.JTable();
        forTeacher = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        tDept = new javax.swing.JComboBox<>();
        tSubmit = new javax.swing.JButton();
        tPassword = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tAddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        TeacherEmail = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        forStudent = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        addStIntake = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addStName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addStSection = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addStEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addStPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addStAddress = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addStSubject = new javax.swing.JComboBox<>();
        SubmitStudentPanel = new javax.swing.JPanel();
        SubmitStudent = new javax.swing.JLabel();
        stPass = new javax.swing.JLabel();
        addStPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        forViewStudent = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudetnsData = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        AddStudentPanel.setBackground(new java.awt.Color(153, 153, 255));
        AddStudentPanel.setForeground(new java.awt.Color(255, 255, 255));

        AddStudent1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddStudent1.setForeground(new java.awt.Color(255, 255, 255));
        AddStudent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddStudent1.setText("Add Student");
        AddStudent1.setToolTipText("");
        AddStudent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddStudent1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddStudentPanelLayout = new javax.swing.GroupLayout(AddStudentPanel);
        AddStudentPanel.setLayout(AddStudentPanelLayout);
        AddStudentPanelLayout.setHorizontalGroup(
            AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddStudent1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddStudentPanelLayout.setVerticalGroup(
            AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        AddTeacherPanel.setBackground(new java.awt.Color(153, 153, 255));
        AddTeacherPanel.setPreferredSize(new java.awt.Dimension(274, 37));

        AddTeacher1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddTeacher1.setForeground(new java.awt.Color(255, 255, 255));
        AddTeacher1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddTeacher1.setText("Add Teacher");
        AddTeacher1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTeacher1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddTeacherPanelLayout = new javax.swing.GroupLayout(AddTeacherPanel);
        AddTeacherPanel.setLayout(AddTeacherPanelLayout);
        AddTeacherPanelLayout.setHorizontalGroup(
            AddTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddTeacher1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddTeacherPanelLayout.setVerticalGroup(
            AddTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddTeacher1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        viewStudentPanel.setBackground(new java.awt.Color(153, 153, 255));

        ViewStudentTable1.setBackground(new java.awt.Color(255, 255, 255));
        ViewStudentTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewStudentTable1.setForeground(new java.awt.Color(255, 255, 255));
        ViewStudentTable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewStudentTable1.setText("View Student ");
        ViewStudentTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewStudentTable1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewStudentPanelLayout = new javax.swing.GroupLayout(viewStudentPanel);
        viewStudentPanel.setLayout(viewStudentPanelLayout);
        viewStudentPanelLayout.setHorizontalGroup(
            viewStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewStudentTable1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );
        viewStudentPanelLayout.setVerticalGroup(
            viewStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewStudentTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        viewTeacherPanel.setBackground(new java.awt.Color(153, 153, 255));

        viewTeacherTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewTeacherTable1.setForeground(new java.awt.Color(255, 255, 255));
        viewTeacherTable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewTeacherTable1.setText("View Teacher");
        viewTeacherTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTeacherTable1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewTeacherPanelLayout = new javax.swing.GroupLayout(viewTeacherPanel);
        viewTeacherPanel.setLayout(viewTeacherPanelLayout);
        viewTeacherPanelLayout.setHorizontalGroup(
            viewTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewTeacherTable1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewTeacherPanelLayout.setVerticalGroup(
            viewTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewTeacherTable1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddTeacherPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewStudentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jSeparator1))
                    .addComponent(viewTeacherPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddTeacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewTeacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Teacher Table");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        TeacherDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Teacher id", "User Id ", "Name", "Email", "Phone", "Address", "Dept", "Password"
            }
        ));
        TeacherDataTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TeacherDataTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(TeacherDataTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout forViewTeacherLayout = new javax.swing.GroupLayout(forViewTeacher);
        forViewTeacher.setLayout(forViewTeacherLayout);
        forViewTeacherLayout.setHorizontalGroup(
            forViewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        forViewTeacherLayout.setVerticalGroup(
            forViewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(forViewTeacher);

        forTeacher.setBackground(new java.awt.Color(153, 153, 255));

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Teacher");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        tDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CSE", "EEE", "ECONOMICS", "CIVIL", "MATH", "TEXTILE", "ENGLISH", "BBA" }));

        tSubmit.setText("Submit ");
        tSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSubmitActionPerformed(evt);
            }
        });

        jLabel18.setText("Password");

        jLabel17.setText("Dept");

        jLabel16.setText("Address");

        jLabel14.setText("Phone");

        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });

        TeacherEmail.setText("Email");

        jLabel12.setText("Name");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tName)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TeacherEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tDept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tAddress)
                    .addComponent(tPhone)
                    .addComponent(tEmail)
                    .addComponent(tPassword)
                    .addComponent(tSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeacherEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tDept, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tAddress, tEmail, tPassword, tPhone});

        jScrollPane4.setViewportView(jPanel7);

        javax.swing.GroupLayout forTeacherLayout = new javax.swing.GroupLayout(forTeacher);
        forTeacher.setLayout(forTeacherLayout);
        forTeacherLayout.setHorizontalGroup(
            forTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forTeacherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        forTeacherLayout.setVerticalGroup(
            forTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forTeacherLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
        );

        jPanel1.add(forTeacher);
        forTeacher.getAccessibleContext().setAccessibleName("forTeacher");

        forStudent.setBackground(new java.awt.Color(153, 153, 255));
        forStudent.setPreferredSize(new java.awt.Dimension(556, 511));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Student");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addStIntake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStIntakeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Intake:");

        addStName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStNameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Name :");

        addStSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStSectionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Section:");

        addStEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStEmailActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Email:");

        addStPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStPhoneActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Phone:");

        addStAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStAddressActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Address:");

        addStSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CSE", "CIVIL", "Textile", "BBA", "English", "LAW" }));
        addStSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStSubjectActionPerformed(evt);
            }
        });

        SubmitStudentPanel.setBackground(new java.awt.Color(153, 153, 255));

        SubmitStudent.setBackground(new java.awt.Color(153, 153, 255));
        SubmitStudent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitStudent.setForeground(new java.awt.Color(255, 255, 255));
        SubmitStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubmitStudent.setText("Submit");
        SubmitStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SubmitStudentPanelLayout = new javax.swing.GroupLayout(SubmitStudentPanel);
        SubmitStudentPanel.setLayout(SubmitStudentPanelLayout);
        SubmitStudentPanelLayout.setHorizontalGroup(
            SubmitStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubmitStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        SubmitStudentPanelLayout.setVerticalGroup(
            SubmitStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubmitStudentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SubmitStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stPass.setDisplayedMnemonic('P');
        stPass.setText("Password:");

        addStPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStPasswordActionPerformed(evt);
            }
        });

        jLabel11.setText("Subject :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addStName, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(addStIntake, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(addStSection, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(addStAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(addStEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(addStPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addStSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                    .addComponent(stPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addStPassword))
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SubmitStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addStAddress, addStEmail, addStIntake, addStName, addStPhone, addStSection, jLabel15, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStSection, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stPass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel5);

        javax.swing.GroupLayout forStudentLayout = new javax.swing.GroupLayout(forStudent);
        forStudent.setLayout(forStudentLayout);
        forStudentLayout.setHorizontalGroup(
            forStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forStudentLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        forStudentLayout.setVerticalGroup(
            forStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forStudentLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
        );

        jPanel1.add(forStudent);
        forStudent.getAccessibleContext().setAccessibleName("ForStudent");

        forViewStudent.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View Student");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        StudetnsData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student_ID", "User_ID", "Name", "Email", "Intake", "Section", "Phone", "Address", "Subject", "Passsword"
            }
        ));
        StudetnsData.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                StudetnsDataAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(StudetnsData);

        javax.swing.GroupLayout forViewStudentLayout = new javax.swing.GroupLayout(forViewStudent);
        forViewStudent.setLayout(forViewStudentLayout);
        forViewStudentLayout.setHorizontalGroup(
            forViewStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(forViewStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        forViewStudentLayout.setVerticalGroup(
            forViewStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forViewStudentLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
        );

        jPanel1.add(forViewStudent);
        forViewStudent.getAccessibleContext().setAccessibleName("forViewStudent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStIntakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStIntakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStIntakeActionPerformed

    private void addStNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStNameActionPerformed

    private void addStSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStSectionActionPerformed

    private void addStEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStEmailActionPerformed

    private void addStPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStPhoneActionPerformed

    private void addStAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStAddressActionPerformed

    private void SubmitStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitStudentMouseClicked
        // TODO add your handling code here:
        SubmitStudentPanel.setBackground(Color.white);
        SubmitStudent.setForeground(Color.black);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/university", "root", "");
            Statement stmt = con.createStatement();
            String query = "";
            // System.out.println("database Connected student");

            String Name = addStName.getText();
            String Email = addStEmail.getText();
            String Password = addStPassword.getText();
            String Subject = addStSubject.getSelectedItem().toString();
            String Section = addStSection.getText();
            String Intake = addStIntake.getText();
            String Phone = addStPhone.getText();
            String Address = addStAddress.getText();

            if (Name.equals("") || Email.equals("") || Password.equals("") || Subject.equals("Select") || Section.equals("") || Intake.equals("") || Phone.equals("") || Address.equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill in all the fields!");
            } else {

                String role = "Student";
                query = "INSERT INTO usertable ( Name , Email, Password, Role) VALUES ('" + Name + "','" + Email + "','" + Password + "','" + role + "')";

                int rowsAffected = stmt.executeUpdate(query);

                if (rowsAffected > 0) {

                    query = "SELECT * FROM usertable WHERE Email='" + Email + "' AND Password='" + Password + "'";
                    ResultSet rs = stmt.executeQuery(query);

// Process the result set
                    String userId = null;
                    String userName = null;
                    String userEmail = null;
                    String userPassword = null;
                    String userRole = null;

                    while (rs.next()) {
                        // Retrieve data from the result set
                        userId = rs.getString("id");
                        userName = rs.getString("Name");
                        userEmail = rs.getString("Email");
                        userPassword = rs.getString("Password");
                        userRole = rs.getString("Role");
//                    System.out.println("User ID: " + userId + ", Email: " + userEmail + ", Password: " + userPassword);
                    }
                    query = "INSERT INTO studenttable ( user_ID, Name , Email, Intake, Section, Phone, Address, Subject, Password) VALUES ( '" + userId + "','" + Name + "','" + Email + "','" + Intake + "','" + Section + "', '" + Phone + "','" + Address + "','" + Subject + "', '" + Password + "')";
                    int rowsAffected2 = stmt.executeUpdate(query);

                    if (rowsAffected2 > 0) {
                        addStName.setText("");
                        addStEmail.setText("");
                        addStPassword.setText("");
                        addStSubject.setSelectedItem("Select");
                        addStSection.setText("");
                        addStIntake.setText("");
                        addStPhone.setText("");
                        addStAddress.setText("");

                        JOptionPane.showMessageDialog(this, "Successfully Created User ");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "user not created !");
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitStudentMouseClicked

    private void addStPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStPasswordActionPerformed

    private void StudetnsDataAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_StudetnsDataAncestorAdded
        // TODO add your handling code here:
        loadDataIntoTable();
    }//GEN-LAST:event_StudetnsDataAncestorAdded

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        // TODO add your handling code here:
        forStudent.setVisible(true);
        forTeacher.setVisible(false);
        forViewStudent.setVisible(false);
        forViewTeacher.setVisible(false);
        // addStudent.setForeground(Color.red);
        AddStudentPanel.setBackground(Color.white);

        int red = Integer.parseInt("99", 16);
        int green = Integer.parseInt("99", 16);
        int blue = Integer.parseInt("FF", 16);

        Color myColor = new Color(red, green, blue);

        AddTeacherPanel.setBackground(myColor);
        viewStudentPanel.setBackground(myColor);
        viewTeacherPanel.setBackground(myColor);

        AddStudent1.setForeground(Color.black);
        AddTeacher1.setForeground(Color.white);
        ViewStudentTable1.setForeground(Color.white);
        viewTeacherTable1.setForeground(Color.white);
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailActionPerformed

    private void tSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSubmitActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/university", "root", "");
            Statement stmt = con.createStatement();
            String query = "";
            // System.out.println("Data base connected teacher");

            String Name = tName.getText();
            String Email = tEmail.getText();
            String Phone = tPhone.getText();
            String Password = tPassword.getText();
            String Address = tAddress.getText();
            String Dept = tDept.getSelectedItem().toString();

            if (Name.equals("") || Email.equals("") || Password.equals("") || Dept.equals("Select") || Phone.equals("") || Address.equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill in all the fields!");
            } else {
                String role = "Teacher";
                query = "INSERT INTO usertable ( Name , Email, Password, Role) VALUES ('" + Name + "','" + Email + "','" + Password + "','" + role + "')";

                int rowsAffected = stmt.executeUpdate(query);
                if (rowsAffected > 0) {

                    query = "SELECT * FROM usertable WHERE Email='" + Email + "' AND Password='" + Password + "'";
                    ResultSet rs = stmt.executeQuery(query);

// Process the result set
                    String userId = null;
                    String userName = null;
                    String userEmail = null;
                    String userPassword = null;
                    String userRole = null;

                    while (rs.next()) {
                        // Retrieve data from the result set
                        userId = rs.getString("id");
                        userName = rs.getString("Name");
                        userEmail = rs.getString("Email");
                        userPassword = rs.getString("Password");
                        userRole = rs.getString("Role");
//                    System.out.println("User ID: " + userId + ", Email: " + userEmail + ", Password: " + userPassword);
                    }
                    // System.out.println("User ID: " + userId + ", Email: " + userEmail + ", Password: " + userPassword);

                    query = "INSERT INTO teachertable ( user_ID, Name , Email, Phone, Address, Dept, Password) VALUES ( '" + userId + "','" + Name + "','" + Email + "','" + Phone + "','" + Address + "', '" + Dept + "','" + Password + "')";
                    int rowsAffected2 = stmt.executeUpdate(query);

                    if (rowsAffected2 > 0) {
                        tName.setText("");
                        tEmail.setText("");
                        tPhone.setText("");
                        tDept.setSelectedItem("Select");
                        tPassword.setText("");
                        tAddress.setText("");

                        JOptionPane.showMessageDialog(this, "Successfully Created User ");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "user not created !");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tSubmitActionPerformed

    private void viewTeacherTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTeacherTable1MouseClicked
        // TODO add your handling code here:
        forViewTeacher.setVisible(true);
        forStudent.setVisible(false);
        forTeacher.setVisible(false);
        forViewStudent.setVisible(false);

        // addStudent.setForeground(Color.red); viewTeacherPanel
        viewTeacherPanel.setBackground(Color.white);

        int red = Integer.parseInt("99", 16);
        int green = Integer.parseInt("99", 16);
        int blue = Integer.parseInt("FF", 16);

        Color myColor = new Color(red, green, blue);

        AddTeacherPanel.setBackground(myColor);
        viewStudentPanel.setBackground(myColor);
        AddStudentPanel.setBackground(myColor);

        viewTeacherTable1.setForeground(Color.black);
        AddStudent1.setForeground(Color.white);
        AddTeacher1.setForeground(Color.white);
        ViewStudentTable1.setForeground(Color.white);
    }//GEN-LAST:event_viewTeacherTable1MouseClicked

    private void ViewStudentTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewStudentTable1MouseClicked
        // TODO add your handling code here:
        forViewStudent.setVisible(true);
        forStudent.setVisible(false);
        forTeacher.setVisible(false);
        forViewTeacher.setVisible(false);
        // 9999FF
        viewStudentPanel.setBackground(Color.white);

        int red = Integer.parseInt("99", 16);
        int green = Integer.parseInt("99", 16);
        int blue = Integer.parseInt("FF", 16);

        Color myColor = new Color(red, green, blue);

        AddStudentPanel.setBackground(myColor);
        AddTeacherPanel.setBackground(myColor);
        viewTeacherPanel.setBackground(myColor);

        ViewStudentTable1.setForeground(Color.black);
        AddTeacher1.setForeground(Color.white);
        AddStudent1.setForeground(Color.white);
        viewTeacherTable1.setForeground(Color.white);
    }//GEN-LAST:event_ViewStudentTable1MouseClicked

    private void AddTeacher1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTeacher1MouseClicked
        // TODO add your handling code here:
        forTeacher.setVisible(true);
        forStudent.setVisible(false);
        forViewStudent.setVisible(false);
        forViewTeacher.setVisible(false);

        AddTeacherPanel.setBackground(Color.white);

        int red = Integer.parseInt("99", 16);
        int green = Integer.parseInt("99", 16);
        int blue = Integer.parseInt("FF", 16);

        Color myColor = new Color(red, green, blue);

        AddStudentPanel.setBackground(myColor);
        viewStudentPanel.setBackground(myColor);
        viewTeacherPanel.setBackground(myColor);

        AddTeacher1.setForeground(Color.black);
        AddStudent1.setForeground(Color.white);
        ViewStudentTable1.setForeground(Color.white);
        viewTeacherTable1.setForeground(Color.white);
    }//GEN-LAST:event_AddTeacher1MouseClicked

    private void AddStudent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStudent1MouseClicked
        // TODO add your handling code here:
        forStudent.setVisible(true);
        forTeacher.setVisible(false);
        forViewStudent.setVisible(false);
        forViewTeacher.setVisible(false);
        // addStudent.setForeground(Color.red);
        AddStudentPanel.setBackground(Color.white);

        int red = Integer.parseInt("99", 16);
        int green = Integer.parseInt("99", 16);
        int blue = Integer.parseInt("FF", 16);

        Color myColor = new Color(red, green, blue);

        AddTeacherPanel.setBackground(myColor);
        viewStudentPanel.setBackground(myColor);
        viewTeacherPanel.setBackground(myColor);

        AddStudent1.setForeground(Color.black);
        AddTeacher1.setForeground(Color.white);
        ViewStudentTable1.setForeground(Color.white);
        viewTeacherTable1.setForeground(Color.white);
    }//GEN-LAST:event_AddStudent1MouseClicked

    private void TeacherDataTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TeacherDataTableAncestorAdded
        // TODO add your handling code here:
        loadDataIntoTable2();
    }//GEN-LAST:event_TeacherDataTableAncestorAdded

    private void addStSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStSubjectActionPerformed

    private void loadDataIntoTable() {
        DefaultTableModel model = (DefaultTableModel) StudetnsData.getModel();
        model.setRowCount(0); // Clear existing rows

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/university", "root", "");

            // Prepare SQL query
            String sql = "SELECT Student_ID, user_ID, Name, Email, Intake, Section, Phone, Address, Subject, Password FROM studenttable ORDER BY Student_ID ; ";
            PreparedStatement statement = connection.prepareStatement(sql);

            // Execute query and get result set
            ResultSet resultSet = statement.executeQuery();

            // Populate data into JTable
            while (resultSet.next()) {
                Object[] row = {
                    resultSet.getInt("Student_ID"),
                    resultSet.getInt("user_ID"),
                    resultSet.getString("Name"),
                    resultSet.getString("Email"),
                    resultSet.getString("Intake"),
                    resultSet.getString("Section"),
                    resultSet.getString("Phone"),
                    resultSet.getString("Address"),
                    resultSet.getString("Subject"),
                    resultSet.getString("Password")
                };
                model.addRow(row);
            }

            // Close resources
            // resultSet.close();
            // statement.close();
            // connection.close();
        } catch (SQLException ex) {
            // Handle exceptions
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        private void loadDataIntoTable2() {
        DefaultTableModel model = (DefaultTableModel) TeacherDataTable.getModel();
        model.setRowCount(0); // Clear existing rows

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/university", "root", "");

            // Prepare SQL query
            String sql = "SELECT Teacher_id, user_ID, Name, Email, Phone, Address, Dept , Password FROM teachertable ORDER BY Teacher_id ; ";
            PreparedStatement statement = connection.prepareStatement(sql);

            // Execute query and get result set
            ResultSet resultSet = statement.executeQuery();

            // Populate data into JTable
            while (resultSet.next()) {
                Object[] row = {
                    resultSet.getInt("Teacher_id"),
                    resultSet.getInt("user_ID"),
                    resultSet.getString("Name"),
                    resultSet.getString("Email"),
                    resultSet.getString("Phone"),
                    resultSet.getString("Address"),
                    resultSet.getString("Dept"),
                    resultSet.getString("Password")
                };
                model.addRow(row);
            }

            // Close resources
            // resultSet.close();
            // statement.close();
            // connection.close();
        } catch (SQLException ex) {
            // Handle exceptions
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminPage().setVisible(true);
//            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddStudent1;
    private javax.swing.JPanel AddStudentPanel;
    private javax.swing.JLabel AddTeacher1;
    private javax.swing.JPanel AddTeacherPanel;
    private javax.swing.JTable StudetnsData;
    private javax.swing.JLabel SubmitStudent;
    private javax.swing.JPanel SubmitStudentPanel;
    private javax.swing.JTable TeacherDataTable;
    private javax.swing.JLabel TeacherEmail;
    private javax.swing.JLabel ViewStudentTable1;
    private javax.swing.JTextField addStAddress;
    private javax.swing.JTextField addStEmail;
    private javax.swing.JTextField addStIntake;
    private javax.swing.JTextField addStName;
    private javax.swing.JTextField addStPassword;
    private javax.swing.JTextField addStPhone;
    private javax.swing.JTextField addStSection;
    private javax.swing.JComboBox<String> addStSubject;
    private javax.swing.JPanel forStudent;
    private javax.swing.JPanel forTeacher;
    private javax.swing.JPanel forViewStudent;
    private javax.swing.JPanel forViewTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel stPass;
    private javax.swing.JTextField tAddress;
    private javax.swing.JComboBox<String> tDept;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tPassword;
    private javax.swing.JTextField tPhone;
    private javax.swing.JButton tSubmit;
    private javax.swing.JPanel viewStudentPanel;
    private javax.swing.JPanel viewTeacherPanel;
    private javax.swing.JLabel viewTeacherTable1;
    // End of variables declaration//GEN-END:variables
}
